apiVersion: apps/v1
kind: Deployment
metadata:
  name: xnoise-app-deployment
  labels:
    app: xnoise-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: xnoise-app
  template:
    metadata:
      labels:
        app: xnoise-app
    spec:
      containers:
      - name: xnoise-app
        image: wryandrei/c-test-app:noise
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources: 
          requests:
            memory: "64Mi"
            cpu: "500m"
          limits:
            memory: "64Mi"
            cpu: "1000m" 
