apiVersion: apps/v1
kind: Deployment
metadata:
  name: atest-app-deployment
  labels:
    app: atest-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: atest-app
  template:
    metadata:
      labels:
        app: atest-app
      annotations:
        balloon.balloons.cri-resource-manager.intel.com: lc-pool
    spec:
      containers:
      - name: c-test-app
        image: wryandrei/c-test-app:params
        #command: ["./given_sim"]
        #args: ["--kubelet-insecure-tls"]
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources: 
          requests:
            memory: "64Mi"
            cpu: "2000m"
          limits:
            memory: "1G"
            cpu: "4000m" 
