apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-deployment
  labels:
    app: test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: c-test-app
        image: wryandrei/c-test-app:latest
        command: ["./given_sim"]
        args: ["-c", "10 60 2"]
        imagePullPolicy: Always
        ports:
        - containerPort: 80