apiVersion: apps/v1
kind: Deployment
metadata:
  name: atest-app-deployment
  labels:
    app: atest-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: atest-app
  template:
    metadata:
      labels:
        app: atest-app
    spec:
      containers:
      - name: c-test-app
        image: wryandrei/c-test-app:params
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources: 
          requests:
            memory: "64Mi"
            cpu: "2000m"
          limits:
            memory: "64Mi"
            cpu: "4000m" 
