apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-deployment
  labels:
    app: testo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testo
  template:
    metadata:
      labels:
        app: testo
    spec:
      containers:
      - name: testo
        image: test-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80